package schemadoc

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Airgap-Castaways/deck/internal/schemafacts"
	"github.com/Airgap-Castaways/deck/internal/workflowcontext"
	"github.com/Airgap-Castaways/deck/internal/workflowexec"
)

type PageInput struct {
	Group        string
	PageSlug     string
	Title        string
	Summary      string
	Description  string
	WhenToUse    string
	TypicalFlows []GroupFlow
	SeeAlso      []string
	Variants     []VariantInput
}

type PhaseInput struct {
	Key         string
	Title       string
	Description string
}

type StepKindPage struct {
	Phase   PhaseInput
	Group   PageInput
	Variant VariantInput
}

type VariantInput struct {
	Kind        string
	Title       string
	Description string
	Schema      map[string]any
	Meta        ToolMetadata
	Required    []string
	Spec        map[string]any
	Outputs     []string
	Roles       []string
	GroupOrder  int
	DocsOrder   int
}

type PageOverrides struct {
	FieldDocs map[string]FieldDoc
	Example   string
	Notes     []string
}

type Field = schemafacts.FieldFact

func DisplayFamilyTitle(family string, preferred string) string {
	if strings.TrimSpace(preferred) != "" {
		return strings.TrimSpace(preferred)
	}
	return familyTitleFallback(family)
}

func RenderStepKindsPage(inputs []PageInput) []byte {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# Step Kinds\n\n")
	buf.WriteString("Choose workflow step kinds by phase and task-oriented group.\n\n")
	buf.WriteString("Use these pages when you are deciding which `kind` to author. For shared step envelope rules, see [Step Envelope Contract](workflow-model.md#step-envelope-contract). For top-level workflow and component document contracts, see [Workflow Model](workflow-model.md#workflow-schema-contract) and [Workspace Layout](workspace-layout.md#component-fragment-contract).\n\n")
	stepPages := StepKindPages(inputs)
	for _, phase := range StepKindPhases() {
		phasePages := stepKindPagesForPhase(stepPages, phase.Key)
		if len(phasePages) == 0 {
			continue
		}
		buf.WriteString("## " + phase.Title + "\n\n")
		buf.WriteString(phase.Description + "\n")
		currentGroup := ""
		for _, page := range phasePages {
			if page.Group.Group != currentGroup {
				if currentGroup != "" {
					buf.WriteString("\n")
				}
				currentGroup = page.Group.Group
				buf.WriteString("\n### " + page.Group.Title + "\n\n")
				if strings.TrimSpace(page.Group.WhenToUse) != "" {
					buf.WriteString(page.Group.WhenToUse + "\n\n")
				}
				buf.WriteString("| Step Kind | Summary |\n")
				buf.WriteString("|---|---|\n")
			}
			path := "step-kinds/" + StepKindSlug(page.Variant.Kind) + ".md"
			buf.WriteString("| [" + page.Variant.Kind + "](" + path + ") | " + escapeMarkdownTableCell(firstNonEmpty(page.Variant.Meta.Summary, page.Variant.Description)) + " |\n")
		}
		buf.WriteString("\n")
	}
	return buf.Bytes()
}

func RenderStepKindPage(in StepKindPage) []byte {
	variant := in.Variant
	facts := schemafacts.Analyze(variant.Schema)
	fields := append([]schemafacts.FieldFact(nil), facts.Fields...)
	applyFieldDocs(fields, variant.Meta.FieldDocs)
	rules := schemafacts.ExtractRules(variant.Spec, "spec")

	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by make generate; DO NOT EDIT. -->\n")
	buf.WriteString("# " + variant.Kind + "\n\n")
	buf.WriteString(firstNonEmpty(variant.Meta.Summary, variant.Description) + "\n\n")
	buf.WriteString("## Summary\n\n")
	buf.WriteString("- kind: `" + variant.Kind + "`\n")
	buf.WriteString("- phase: `" + in.Phase.Key + "`\n")
	buf.WriteString("- group: " + in.Group.Title + "\n")
	if len(variant.Outputs) > 0 {
		buf.WriteString("- outputs: `" + strings.Join(variant.Outputs, "`, `") + "`\n")
	}
	if strings.TrimSpace(variant.Meta.WhenToUse) != "" {
		buf.WriteString("\n## When To Use\n\n" + variant.Meta.WhenToUse + "\n")
	}
	buf.WriteString("\n## Example\n\n```yaml\n")
	example, err := toolExample(variant)
	if err != nil {
		buf.WriteString("# error: unable to render example\n")
		buf.WriteString("```\n")
		return buf.Bytes()
	}
	buf.WriteString(example)
	buf.WriteString("```\n")
	buf.WriteString("\n## Spec Fields\n\n")
	buf.WriteString(renderFieldTable(directChildFields(fields, "spec")))
	if nested := renderNestedSections(fields, "spec"); nested != "" {
		buf.WriteString("\n## Nested Objects\n\n")
		buf.WriteString(nested)
	}
	if len(rules) > 0 {
		buf.WriteString("\n## Validation Rules\n\n")
		for _, rule := range rules {
			buf.WriteString("- " + rule + "\n")
		}
	}
	if len(variant.Meta.Notes) > 0 {
		buf.WriteString("\n## Notes\n\n")
		for _, note := range variant.Meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	buf.WriteString("\n## Related\n\n")
	for _, related := range sortedVariants(in.Group.Variants) {
		if related.Kind == variant.Kind {
			continue
		}
		buf.WriteString("- [" + related.Kind + "](" + StepKindSlug(related.Kind) + ".md)\n")
	}
	buf.WriteString("- [Step Kinds](../step-kinds.md)\n")
	buf.WriteString("- [Step Envelope Contract](../workflow-model.md#step-envelope-contract)\n")
	return buf.Bytes()
}

func StepKindPhases() []PhaseInput {
	return []PhaseInput{
		{Key: "prepare", Title: "Prepare", Description: "Use these kinds in prepare workflows that produce bundle artifacts or collect local preflight facts."},
		{Key: "apply", Title: "Apply", Description: "Use these kinds in apply workflows that mutate or verify target nodes."},
		{Key: "common", Title: "Common", Description: "Use these kinds in prepare or apply workflows."},
	}
}

func StepKindPages(inputs []PageInput) []StepKindPage {
	pages := make([]StepKindPage, 0)
	for _, group := range inputs {
		for _, variant := range sortedVariants(group.Variants) {
			pages = append(pages, StepKindPage{Phase: phaseForRoles(variant.Roles), Group: group, Variant: variant})
		}
	}
	sort.Slice(pages, func(i, j int) bool {
		if pages[i].Phase.Key != pages[j].Phase.Key {
			return phaseOrder(pages[i].Phase.Key) < phaseOrder(pages[j].Phase.Key)
		}
		leftMeta := MustGroupMeta(pages[i].Group.Group)
		rightMeta := MustGroupMeta(pages[j].Group.Group)
		if leftMeta.Order != rightMeta.Order {
			return leftMeta.Order < rightMeta.Order
		}
		if pages[i].Variant.GroupOrder != pages[j].Variant.GroupOrder {
			return pages[i].Variant.GroupOrder < pages[j].Variant.GroupOrder
		}
		if pages[i].Variant.DocsOrder != pages[j].Variant.DocsOrder {
			return pages[i].Variant.DocsOrder < pages[j].Variant.DocsOrder
		}
		return pages[i].Variant.Kind < pages[j].Variant.Kind
	})
	return pages
}

func stepKindPagesForPhase(pages []StepKindPage, phase string) []StepKindPage {
	out := make([]StepKindPage, 0)
	for _, page := range pages {
		if page.Phase.Key == phase {
			out = append(out, page)
		}
	}
	return out
}

func phaseForRoles(roles []string) PhaseInput {
	hasPrepare := containsString(roles, "prepare")
	hasApply := containsString(roles, "apply")
	for _, phase := range StepKindPhases() {
		switch phase.Key {
		case "prepare":
			if hasPrepare && !hasApply {
				return phase
			}
		case "apply":
			if hasApply && !hasPrepare {
				return phase
			}
		case "common":
			if hasPrepare && hasApply {
				return phase
			}
		}
	}
	return PhaseInput{Key: "apply", Title: "Apply", Description: "Use these kinds in apply workflows that mutate or verify target nodes."}
}

func phaseOrder(phase string) int {
	for i, item := range StepKindPhases() {
		if item.Key == phase {
			return i
		}
	}
	return len(StepKindPhases())
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if strings.TrimSpace(value) == want {
			return true
		}
	}
	return false
}

func RenderWorkflowSchemaPartial(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	return renderCoreSchemaSection("## Workflow Schema Contract", schemaPath, schema, meta, true)
}

func RenderToolDefinitionSchemaPartial(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	return renderCoreSchemaSection("## Tool Definition Contract", schemaPath, schema, meta, true)
}

func RenderComponentFragmentSchemaPartial(schemaPath string, schema map[string]any, meta PageMetadata) []byte {
	return renderCoreSchemaSection("#### Component Fragment Contract", schemaPath, schema, meta, false)
}

func RenderSystemVariablesPartial() []byte {
	var buf bytes.Buffer
	buf.WriteString("### Built-In Runtime Fields\n\n")
	buf.WriteString("`runtime.host` is a built-in reserved runtime namespace in both prepare and apply. Use it for detected host facts such as OS family, distro ID, version, architecture, and kernel release. Do not model detected local host facts as static `vars` values.\n\n")
	buf.WriteString(renderRuntimeFieldTable(workflowexec.RuntimeHostFieldDefinitions()))
	buf.WriteString("\n### Execution Context Fields\n\n")
	buf.WriteString("`context` is available in both `when` expressions and templates. Canonical fields are:\n\n")
	buf.WriteString(renderContextFieldTable(workflowcontext.FieldDefinitions()))
	buf.WriteString("\nLegacy aliases remain available for existing templates: `context.bundleRoot` maps to `context.paths.bundleRoot`, and `context.stateFile` maps to `context.paths.stateFile`.\n\n")
	buf.WriteString("When apply state keys are computed, deck includes a fingerprint of the execution context except fields derived from other context values, such as `context.workflow.isServer`, and `context.paths.stateFile`, which is derived from the state key itself.\n")
	return buf.Bytes()
}

func renderRuntimeFieldTable(fields []workflowexec.RuntimeFieldDefinition) string {
	if len(fields) == 0 {
		return "No documented runtime fields.\n"
	}
	var buf bytes.Buffer
	buf.WriteString("| Field | Type | Description |\n")
	buf.WriteString("|---|---|---|\n")
	for _, field := range fields {
		buf.WriteString("| `" + escapePipe(field.Path) + "` | `" + escapePipe(field.Type) + "` | " + escapeMarkdownTableCell(field.Description) + " |\n")
	}
	return buf.String()
}

func renderContextFieldTable(fields []workflowcontext.FieldDefinition) string {
	if len(fields) == 0 {
		return "No documented context fields.\n"
	}
	var buf bytes.Buffer
	buf.WriteString("| Field | Type | Prepare | Apply | Description |\n")
	buf.WriteString("|---|---|---:|---:|---|\n")
	for _, field := range fields {
		buf.WriteString("| `" + escapePipe(field.Path) + "` | `" + escapePipe(field.Type) + "` | " + yesNo(field.Prepare) + " | " + yesNo(field.Apply) + " | " + escapeMarkdownTableCell(field.Description) + " |\n")
	}
	return buf.String()
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func renderCoreSchemaSection(heading string, schemaPath string, schema map[string]any, meta PageMetadata, includeValidation bool) []byte {
	var buf bytes.Buffer
	sectionLevel := strings.Count(strings.SplitN(strings.TrimSpace(heading), " ", 2)[0], "#")
	childHeading := strings.Repeat("#", sectionLevel+1)
	buf.WriteString(heading + "\n\n")
	buf.WriteString(firstNonEmpty(meta.Summary, "Schema reference.") + "\n\n")
	buf.WriteString("- schema: `" + schemaPath + "`\n\n")
	buf.WriteString(childHeading + " Example\n\n```yaml\n" + firstNonEmpty(meta.Example, "version: v1alpha1\nsteps:\n  - id: example-step\n    kind: WriteFile\n    spec:\n      path: /tmp/example\n      content: hello\n") + "```\n")
	facts := schemafacts.Analyze(schema)
	fields := append([]schemafacts.FieldFact(nil), facts.Fields...)
	applyFieldDocs(fields, meta.FieldDocs)
	buf.WriteString("\n" + childHeading + " Fields\n\n")
	buf.WriteString(renderFieldTable(schemafacts.FilterDirectChildFields(fields, "")))
	if nested := renderNestedSections(fields, ""); nested != "" {
		buf.WriteString("\n" + childHeading + " Nested Objects\n\n")
		buf.WriteString(nested)
	}
	if includeValidation {
		buf.WriteString("\n" + childHeading + " Validation Rules\n\n")
		for _, rule := range facts.RuleSummaries {
			buf.WriteString("- " + rule + "\n")
		}
	}
	if len(meta.Notes) > 0 {
		buf.WriteString("\n" + childHeading + " Notes\n\n")
		for _, note := range meta.Notes {
			buf.WriteString("- " + note + "\n")
		}
	}
	return buf.Bytes()
}

func StepKindSlug(kind string) string {
	kind = strings.TrimSpace(kind)
	if kind == "" {
		return "step-kind"
	}
	var buf strings.Builder
	runes := []rune(kind)
	for i, r := range runes {
		if r >= 'A' && r <= 'Z' {
			if i > 0 && (isLowerASCII(runes[i-1]) || (i+1 < len(runes) && isLowerASCII(runes[i+1]))) {
				buf.WriteByte('-')
			}
			buf.WriteRune(r + ('a' - 'A'))
			continue
		}
		buf.WriteRune(r)
	}
	return buf.String()
}

func isLowerASCII(r rune) bool {
	return r >= 'a' && r <= 'z'
}

func sortedVariants(variants []VariantInput) []VariantInput {
	out := append([]VariantInput(nil), variants...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].GroupOrder != out[j].GroupOrder {
			return out[i].GroupOrder < out[j].GroupOrder
		}
		if out[i].DocsOrder != out[j].DocsOrder {
			return out[i].DocsOrder < out[j].DocsOrder
		}
		return out[i].Kind < out[j].Kind
	})
	return out
}

func toolExample(in VariantInput) (string, error) {
	if strings.TrimSpace(in.Meta.Example) != "" {
		return in.Meta.Example, nil
	}
	obj := map[string]any{
		"id":         "example-" + strings.ToLower(in.Kind),
		"apiVersion": "deck/v1alpha1",
		"kind":       in.Kind,
		"spec":       minimalObject(in.Spec),
	}
	raw, err := yaml.Marshal(obj)
	if err != nil {
		return "", fmt.Errorf("marshal minimal tool example: %w", err)
	}
	return string(raw), nil
}

func applyFieldDocs(fields []Field, overrides map[string]FieldDoc) {
	for i := range fields {
		override, ok := overrides[fields[i].Path]
		if !ok {
			continue
		}
		if strings.TrimSpace(override.Description) != "" {
			fields[i].Description = override.Description
		}
		if strings.TrimSpace(override.Example) != "" {
			fields[i].Example = override.Example
		}
	}
}

func minimalObject(node map[string]any) map[string]any {
	obj := map[string]any{}
	req := requiredSet(node["required"])
	props, _ := node["properties"].(map[string]any)
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child, _ := props[key].(map[string]any)
		if !req[key] && key != "action" {
			continue
		}
		obj[key] = minimalValue(node, child)
	}
	if allOf, ok := node["allOf"].([]any); ok {
		for _, raw := range allOf {
			entry, _ := raw.(map[string]any)
			action := stringValue(mapValue(entry, "if", "properties", "action", "const"))
			if action != "" {
				obj["action"] = action
				for _, field := range toStrings(mapValue(entry, "then", "required")) {
					if child, ok := props[field].(map[string]any); ok {
						obj[field] = minimalValue(node, child)
					}
				}
				for _, anyRaw := range toAnySliceFromUnknown(mapValue(entry, "then", "anyOf")) {
					choice, _ := anyRaw.(map[string]any)
					for _, field := range toStrings(choice["required"]) {
						if child, ok := props[field].(map[string]any); ok {
							obj[field] = minimalValue(node, child)
							break
						}
					}
					break
				}
				break
			}
		}
	}
	applyBranchRequirements(obj, node, props)
	return obj
}

func applyBranchRequirements(obj map[string]any, node map[string]any, props map[string]any) {
	for _, groupKey := range []string{"anyOf", "oneOf"} {
		for _, raw := range toAnySliceFromUnknown(node[groupKey]) {
			branch, _ := raw.(map[string]any)
			for _, field := range toStrings(branch["required"]) {
				if _, exists := obj[field]; exists {
					continue
				}
				if child, ok := props[field].(map[string]any); ok {
					obj[field] = minimalValue(node, child)
					return
				}
			}
		}
	}
}

func minimalValue(root, node map[string]any) any {
	node = resolveSchemaNode(root, node)
	if value := node["const"]; value != nil {
		return value
	}
	if values := toStrings(node["enum"]); len(values) > 0 {
		return values[0]
	}
	switch fieldType(root, node) {
	case "string":
		return "example"
	case "integer":
		return 1
	case "number":
		return 1
	case "boolean":
		return true
	case "array<string>":
		return []string{"example"}
	case "array<object>":
		items, _ := node["items"].(map[string]any)
		return []any{minimalObject(resolveSchemaNode(root, items))}
	case "array":
		return []any{"example"}
	case "object":
		return minimalObject(node)
	default:
		return "example"
	}
}

func renderFieldTable(fields []Field) string {
	if len(fields) == 0 {
		return "No documented fields.\n"
	}
	var buf bytes.Buffer
	buf.WriteString("| Key | Type | Required | Default | Enum | Description | Example |\n")
	buf.WriteString("|---|---|---:|---|---|---|---|\n")
	for _, field := range fields {
		buf.WriteString("| `" + escapePipe(field.Path) + "` | `" + escapePipe(field.Type) + "` | ")
		if field.Required {
			buf.WriteString("yes")
		} else {
			buf.WriteString("no")
		}
		buf.WriteString(" | `" + escapePipe(field.Default) + "` | `" + escapePipe(strings.Join(field.Enum, ", ")) + "` | " + escapeMarkdownTableCell(field.Description) + " | `" + escapeMarkdownTableCell(field.Example) + "` |\n")
	}
	return buf.String()
}

func filterFields(fields []Field, keep func(Field) bool) []Field {
	var out []Field
	for _, field := range fields {
		if keep(field) {
			out = append(out, field)
		}
	}
	return out
}

func requiredSet(raw any) map[string]bool {
	set := map[string]bool{}
	for _, item := range toStrings(raw) {
		set[item] = true
	}
	return set
}

func fieldType(root, node map[string]any) string {
	node = resolveSchemaNode(root, node)
	if t, _ := node["type"].(string); t != "" {
		if t == "array" {
			items, _ := node["items"].(map[string]any)
			items = resolveSchemaNode(root, items)
			if itemType, _ := items["type"].(string); itemType != "" {
				return "array<" + itemType + ">"
			}
			if len(items) > 0 {
				return "array<object>"
			}
		}
		return t
	}
	if node["const"] != nil {
		return "string"
	}
	if node["properties"] != nil {
		return "object"
	}
	return "unknown"
}

func renderNestedSections(fields []Field, prefix string) string {
	sections := nestedSectionPaths(fields, prefix)
	if len(sections) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for _, section := range sections {
		sectionFields := directChildFields(fields, section)
		if len(sectionFields) == 0 {
			continue
		}
		buf.WriteString("### `" + section + "`\n\n")
		buf.WriteString(renderFieldTable(sectionFields))
		buf.WriteString("\n")
	}
	return buf.String()
}

func directChildFields(fields []Field, prefix string) []Field {
	return filterFields(fields, func(f Field) bool {
		if prefix == "" {
			return !strings.Contains(f.Path, ".") && !strings.Contains(f.Path, "[]")
		}
		if !strings.HasPrefix(f.Path, prefix+".") && !strings.HasPrefix(f.Path, prefix+"[]") {
			return false
		}
		remainder := strings.TrimPrefix(strings.TrimPrefix(f.Path, prefix+"."), prefix+"[]")
		return !strings.Contains(remainder, ".") && !strings.Contains(remainder, "[]")
	})
}

func nestedSectionPaths(fields []Field, prefix string) []string {
	seen := map[string]bool{}
	var out []string
	for _, field := range fields {
		if field.Type != "object" && field.Type != "array<object>" {
			continue
		}
		if field.Path == "" || !strings.Contains(field.Path, ".") {
			if prefix == "" || field.Path == prefix {
				continue
			}
		}
		if prefix != "" && !strings.HasPrefix(field.Path, prefix+".") {
			continue
		}
		if seen[field.Path] {
			continue
		}
		seen[field.Path] = true
		out = append(out, field.Path)
	}
	sort.Strings(out)
	return out
}

func resolveSchemaNode(root, node map[string]any) map[string]any {
	if node == nil {
		return nil
	}
	ref, _ := node["$ref"].(string)
	if ref == "" || !strings.HasPrefix(ref, "#/") {
		return node
	}
	parts := strings.Split(strings.TrimPrefix(ref, "#/"), "/")
	var current any = root
	for _, part := range parts {
		m, ok := current.(map[string]any)
		if !ok {
			return node
		}
		current = m[part]
	}
	resolved, ok := current.(map[string]any)
	if !ok {
		return node
	}
	return resolved
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func toStrings(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func mapValue(root any, path ...string) any {
	current, _ := root.(map[string]any)
	for _, key := range path {
		if current == nil {
			return nil
		}
		next := current[key]
		if m, ok := next.(map[string]any); ok {
			current = m
			continue
		}
		if key == path[len(path)-1] {
			return next
		}
		return nil
	}
	return current
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func familyTitleFallback(family string) string {
	if family == "" {
		return ""
	}
	parts := strings.Split(family, "-")
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, " ")
}

func toAnySliceFromUnknown(v any) []any { items, _ := v.([]any); return items }

func escapePipe(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

func escapeMarkdownTableCell(s string) string {
	return strings.ReplaceAll(escapePipe(s), "\n", "<br>")
}
