package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenDocsWritesPerCommandMarkdown(t *testing.T) {
	dir := t.TempDir()
	root := newRootCommand(newCLIEnv(nil, nil))
	if err := runGenDocs(root, dir); err != nil {
		t.Fatalf("runGenDocs: %v", err)
	}

	for _, name := range []string{"deck.md", "deck_apply.md", "deck_prepare.md", "deck_bundle.md"} {
		p := filepath.Join(dir, name)
		if _, err := os.Stat(p); err != nil {
			t.Fatalf("expected generated %s: %v", name, err)
		}
	}

	b, err := os.ReadFile(filepath.Join(dir, "deck_apply.md"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "Auto generated by spf13/cobra on") {
		t.Fatal("generated docs must not contain a date stamp; set DisableAutoGenTag")
	}

	leaf, err := os.ReadFile(filepath.Join(dir, "deck_bundle_build.md"))
	if err != nil {
		t.Fatalf("expected nested leaf doc: %v", err)
	}
	if strings.Contains(string(leaf), "Auto generated by spf13/cobra on") {
		t.Fatal("nested leaf command must not contain a date stamp")
	}
}
