import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'installation',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['quick-start', 'offline-kubernetes'],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'core-concepts/README'},
      items: [
        'core-concepts/why-deck',
        'core-concepts/lifecycle',
        'core-concepts/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/authoring-workflows',
        'guides/variables-and-templating',
        'guides/conditions-and-cel',
        'guides/phases-and-parallelism',
        'guides/capturing-output',
        'guides/running-the-server',
        'ask',
        'examples/README',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'workflow-model',
        'workspace-layout',
        'bundle-layout',
        'deckignore',
        'apply-state',
        'apply-runlogs',
        {
          type: 'category',
          label: 'Server',
          items: ['server/registry', 'server/daemon', 'server-audit-log'],
        },
        {
          type: 'category',
          label: 'CLI Reference',
          link: {type: 'doc', id: 'cli'},
          items: [{type: 'autogenerated', dirName: 'cli'}],
        },
        {
          type: 'category',
          label: 'Step Kinds',
          link: {type: 'doc', id: 'step-kinds'},
          items: [{type: 'autogenerated', dirName: 'step-kinds'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Diagnostics',
      items: ['diagnostics/error-codes', 'troubleshooting', 'glossary'],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;
