import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['quick-start', 'offline-kubernetes', 'examples/README'],
    },
    {
      type: 'category',
      label: 'Authoring',
      items: ['workflow-model', 'step-kinds', 'workspace-layout'],
    },
    {
      type: 'category',
      label: 'Prepare & Bundle',
      items: ['bundle-layout', 'deckignore'],
    },
    {
      type: 'category',
      label: 'Apply & Operate',
      items: ['apply-state', 'apply-runlogs', 'server/registry', 'server/daemon', 'server-audit-log', 'diagnostics/error-codes'],
    },
    {
      type: 'category',
      label: 'deck ask',
      items: ['ask'],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      link: {type: 'doc', id: 'cli'},
      items: [{type: 'autogenerated', dirName: 'cli'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'core-concepts/README'},
      items: ['core-concepts/why-deck', 'core-concepts/architecture'],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;
